from datetime import datetime, timezone
import random


def zuluTime():
    return str(datetime.now(timezone.utc).isoformat().replace("+00:00", "Z"))


def smartTool_TIGHTENINGRESULT():
    return {
        "TagType": "DataTag",
        "Name": "TIGHTENINGRESULT",
        "DataType": "Object",
        "IOType": "In",
        "Units": "",
        "PublishedTimeStamp": zuluTime(),
        "Parameters": {"TOOLNAME": "SMARTTOOL1"},
        "Readings": [
            {
                "TimeStamp": zuluTime(),
                "Value": {
                    "TotalNumberOfMessages": 2,
                    "MessageNumber": 1,
                    "ResultDataIdentifier": 600,
                    "Time": zuluTime(),
                    "ResultStatus": False,
                    "OperationType": 0,
                    "NumberOfObjects": 1,
                    "NumberOfDataFields": 0,
                    "ObjectDataList": [{"Id": 0, "Status": True}],
                    "VariableDataFields": [],
                    "RevisionsByFields": {
                        "1": [
                            {
                                "HasPrefix": False,
                                "Field": i,
                                "Index": 20 + i * 3,
                                "Size": random.choice([0, 1, 2, 3, 4, 5, 6, 10]),
                                "Value": random.choice(
                                    ["", "0", "00", "002", "001", "0000000600", "2022"]
                                ),
                                "RawValue": None,
                            }
                            for i in range(10)
                        ]
                    },
                    "HeaderData": {
                        "Length": 69,
                        "Mid": 1201,
                        "Revision": 1,
                        "NoAckFlag": 0,
                        "SpindleID": None,
                        "StationID": None,
                        "UsedAs": None,
                    },
                },
                "Quality": 1.0,
            }
        ],
    }


def smartTool_TIGHTENINGDATA():
    return {
        "TagType": "DataTag",
        "Name": "TIGHTENINGDATA",
        "DataType": "Object",
        "IOType": "In",
        "Units": "",
        "PublishedTimeStamp": zuluTime(),
        "Parameters": {"TOOLNAME": "341532435BC802000000043F"},
        "Readings": [
            {
                "TimeStamp": zuluTime(),
                "Value": {
                    "TotalNumberOfMessages": 2,
                    "MessageNumber": 2,
                    "ResultDataIdentifier": 600,
                    "ObjectId": 0,
                    "NumberOfDataFields": 76,
                    "VariableDataFields": [
                        {
                            "ParameterId": 30200,
                            "Length": 11,
                            "DataType": 2,
                            "Unit": 0,
                            "StepNumber": 0,
                            "RealValue": "00000000600",
                        },
                        {
                            "ParameterId": 30201,
                            "Length": 1,
                            "DataType": 2,
                            "Unit": 0,
                            "StepNumber": 0,
                            "RealValue": "1",
                        },
                        {
                            "ParameterId": 30202,
                            "Length": 1,
                            "DataType": 2,
                            "Unit": 0,
                            "StepNumber": 0,
                            "RealValue": "3",
                        },
                        {
                            "ParameterId": 30203,
                            "Length": 19,
                            "DataType": 5,
                            "Unit": 0,
                            "StepNumber": 0,
                            "RealValue": "2022-01-10:17:30:58",
                        },
                        {
                            "ParameterId": 30204,
                            "Length": 1,
                            "DataType": 2,
                            "Unit": 0,
                            "StepNumber": 0,
                            "RealValue": "1",
                        },
                        {
                            "ParameterId": 30205,
                            "Length": 2,
                            "DataType": 2,
                            "Unit": 0,
                            "StepNumber": 0,
                            "RealValue": "02",
                        },
                        {
                            "ParameterId": 30206,
                            "Length": 2,
                            "DataType": 2,
                            "Unit": 0,
                            "StepNumber": 0,
                            "RealValue": "09",
                        },
                        {
                            "ParameterId": 30207,
                            "Length": 8,
                            "DataType": 4,
                            "Unit": 0,
                            "StepNumber": 0,
                            "RealValue": "C3630057",
                        },
                        {
                            "ParameterId": 30208,
                            "Length": 11,
                            "DataType": 4,
                            "Unit": 0,
                            "StepNumber": 0,
                            "RealValue": "Industreweb",
                        },
                        {
                            "ParameterId": 30209,
                            "Length": 1,
                            "DataType": 2,
                            "Unit": 0,
                            "StepNumber": 0,
                            "RealValue": "0",
                        },
                        {
                            "ParameterId": 30210,
                            "Length": 0,
                            "DataType": 4,
                            "Unit": 0,
                            "StepNumber": 0,
                            "RealValue": "",
                        },
                        {
                            "ParameterId": 30211,
                            "Length": 1,
                            "DataType": 2,
                            "Unit": 0,
                            "StepNumber": 0,
                            "RealValue": "0",
                        },
                        {
                            "ParameterId": 30212,
                            "Length": 0,
                            "DataType": 4,
                            "Unit": 0,
                            "StepNumber": 0,
                            "RealValue": "",
                        },
                        {
                            "ParameterId": 30213,
                            "Length": 1,
                            "DataType": 2,
                            "Unit": 0,
                            "StepNumber": 0,
                            "RealValue": "0",
                        },
                        {
                            "ParameterId": 30214,
                            "Length": 8,
                            "DataType": 4,
                            "Unit": 0,
                            "StepNumber": 0,
                            "RealValue": "B3530897",
                        },
                        {
                            "ParameterId": 30215,
                            "Length": 16,
                            "DataType": 4,
                            "Unit": 0,
                            "StepNumber": 0,
                            "RealValue": "ETD MT41-150-I06",
                        },
                        {
                            "ParameterId": 30216,
                            "Length": 3,
                            "DataType": 2,
                            "Unit": 0,
                            "StepNumber": 0,
                            "RealValue": "003",
                        },
                        {
                            "ParameterId": 30217,
                            "Length": 7,
                            "DataType": 4,
                            "Unit": 0,
                            "StepNumber": 0,
                            "RealValue": "1.50 Nm",
                        },
                        {
                            "ParameterId": 30218,
                            "Length": 9,
                            "DataType": 2,
                            "Unit": 0,
                            "StepNumber": 0,
                            "RealValue": "000000001",
                        },
                        {
                            "ParameterId": 30219,
                            "Length": 19,
                            "DataType": 5,
                            "Unit": 0,
                            "StepNumber": 0,
                            "RealValue": "2021-11-04:12:49:40",
                        },
                        {
                            "ParameterId": 30220,
                            "Length": 19,
                            "DataType": 5,
                            "Unit": 0,
                            "StepNumber": 0,
                            "RealValue": "2021-11-04:12:49:40",
                        },
                        {
                            "ParameterId": 30221,
                            "Length": 5,
                            "DataType": 2,
                            "Unit": 0,
                            "StepNumber": 0,
                            "RealValue": "00000",
                        },
                        {
                            "ParameterId": 30222,
                            "Length": 0,
                            "DataType": 4,
                            "Unit": 0,
                            "StepNumber": 0,
                            "RealValue": "",
                        },
                        {
                            "ParameterId": 30223,
                            "Length": 9,
                            "DataType": 2,
                            "Unit": 0,
                            "StepNumber": 0,
                            "RealValue": "000000000",
                        },
                        {
                            "ParameterId": 30226,
                            "Length": 5,
                            "DataType": 2,
                            "Unit": 0,
                            "StepNumber": 0,
                            "RealValue": "00000",
                        },
                        {
                            "ParameterId": 30227,
                            "Length": 5,
                            "DataType": 2,
                            "Unit": 0,
                            "StepNumber": 0,
                            "RealValue": "00000",
                        },
                        {
                            "ParameterId": 30228,
                            "Length": 3,
                            "DataType": 2,
                            "Unit": 0,
                            "StepNumber": 0,
                            "RealValue": "000",
                        },
                        {
                            "ParameterId": 30229,
                            "Length": 3,
                            "DataType": 2,
                            "Unit": 0,
                            "StepNumber": 0,
                            "RealValue": "000",
                        },
                        {
                            "ParameterId": 30254,
                            "Length": 3,
                            "DataType": 2,
                            "Unit": 0,
                            "StepNumber": 0,
                            "RealValue": "000",
                        },
                        {
                            "ParameterId": 30230,
                            "Length": 12,
                            "DataType": 90,
                            "Unit": 1,
                            "StepNumber": 0,
                            "RealValue": "0003.411e-02",
                        },
                        {
                            "ParameterId": 30231,
                            "Length": 12,
                            "DataType": 90,
                            "Unit": 50,
                            "StepNumber": 0,
                            "RealValue": "0001.082e+04",
                        },
                        {
                            "ParameterId": 30270,
                            "Length": 12,
                            "DataType": 90,
                            "Unit": 50,
                            "StepNumber": 0,
                            "RealValue": "0001.080e+04",
                        },
                        {
                            "ParameterId": 30232,
                            "Length": 12,
                            "DataType": 90,
                            "Unit": 200,
                            "StepNumber": 0,
                            "RealValue": "0002.664e+00",
                        },
                        {
                            "ParameterId": 30233,
                            "Length": 12,
                            "DataType": 90,
                            "Unit": 251,
                            "StepNumber": 0,
                            "RealValue": "0002.313e+01",
                        },
                        {
                            "ParameterId": 30234,
                            "Length": 1,
                            "DataType": 2,
                            "Unit": 0,
                            "StepNumber": 0,
                            "RealValue": "3",
                        },
                        {
                            "ParameterId": 30271,
                            "Length": 1,
                            "DataType": 2,
                            "Unit": 0,
                            "StepNumber": 0,
                            "RealValue": "3",
                        },
                        {
                            "ParameterId": 30235,
                            "Length": 1,
                            "DataType": 2,
                            "Unit": 0,
                            "StepNumber": 0,
                            "RealValue": "1",
                        },
                        {
                            "ParameterId": 30236,
                            "Length": 1,
                            "DataType": 2,
                            "Unit": 0,
                            "StepNumber": 0,
                            "RealValue": "1",
                        },
                        {
                            "ParameterId": 30237,
                            "Length": 12,
                            "DataType": 90,
                            "Unit": 1,
                            "StepNumber": 0,
                            "RealValue": "0003.411e-02",
                        },
                        {
                            "ParameterId": 30238,
                            "Length": 12,
                            "DataType": 90,
                            "Unit": 50,
                            "StepNumber": 0,
                            "RealValue": "0001.082e+04",
                        },
                        {
                            "ParameterId": 30239,
                            "Length": 1,
                            "DataType": 2,
                            "Unit": 0,
                            "StepNumber": 0,
                            "RealValue": "1",
                        },
                        {
                            "ParameterId": 30240,
                            "Length": 3,
                            "DataType": 2,
                            "Unit": 0,
                            "StepNumber": 0,
                            "RealValue": "001",
                        },
                        {
                            "ParameterId": 30241,
                            "Length": 1,
                            "DataType": 2,
                            "Unit": 0,
                            "StepNumber": 0,
                            "RealValue": "1",
                        },
                        {
                            "ParameterId": 30242,
                            "Length": 1,
                            "DataType": 2,
                            "Unit": 0,
                            "StepNumber": 0,
                            "RealValue": "3",
                        },
                        {
                            "ParameterId": 30255,
                            "Length": 12,
                            "DataType": 90,
                            "Unit": 1,
                            "StepNumber": 0,
                            "RealValue": "0001.650e+00",
                        },
                        {
                            "ParameterId": 30256,
                            "Length": 12,
                            "DataType": 90,
                            "Unit": 1,
                            "StepNumber": 0,
                            "RealValue": "0000.000e+00",
                        },
                        {
                            "ParameterId": 30257,
                            "Length": 12,
                            "DataType": 90,
                            "Unit": 50,
                            "StepNumber": 0,
                            "RealValue": "0001.080e+04",
                        },
                        {
                            "ParameterId": 30258,
                            "Length": 12,
                            "DataType": 90,
                            "Unit": 50,
                            "StepNumber": 0,
                            "RealValue": "0000.000e+00",
                        },
                        {
                            "ParameterId": 30243,
                            "Length": 12,
                            "DataType": 90,
                            "Unit": 800,
                            "StepNumber": 0,
                            "RealValue": "0000.000e+00",
                        },
                        {
                            "ParameterId": 30244,
                            "Length": 0,
                            "DataType": 4,
                            "Unit": 0,
                            "StepNumber": 0,
                            "RealValue": "",
                        },
                        {
                            "ParameterId": 30245,
                            "Length": 0,
                            "DataType": 4,
                            "Unit": 0,
                            "StepNumber": 0,
                            "RealValue": "",
                        },
                        {
                            "ParameterId": 30246,
                            "Length": 0,
                            "DataType": 4,
                            "Unit": 0,
                            "StepNumber": 0,
                            "RealValue": "",
                        },
                        {
                            "ParameterId": 30247,
                            "Length": 0,
                            "DataType": 4,
                            "Unit": 0,
                            "StepNumber": 0,
                            "RealValue": "",
                        },
                        {
                            "ParameterId": 30248,
                            "Length": 0,
                            "DataType": 4,
                            "Unit": 0,
                            "StepNumber": 0,
                            "RealValue": "",
                        },
                        {
                            "ParameterId": 30249,
                            "Length": 0,
                            "DataType": 4,
                            "Unit": 0,
                            "StepNumber": 0,
                            "RealValue": "",
                        },
                        {
                            "ParameterId": 30250,
                            "Length": 0,
                            "DataType": 4,
                            "Unit": 0,
                            "StepNumber": 0,
                            "RealValue": "",
                        },
                        {
                            "ParameterId": 30251,
                            "Length": 0,
                            "DataType": 4,
                            "Unit": 0,
                            "StepNumber": 0,
                            "RealValue": "",
                        },
                        {
                            "ParameterId": 30252,
                            "Length": 3,
                            "DataType": 2,
                            "Unit": 0,
                            "StepNumber": 0,
                            "RealValue": "000",
                        },
                        {
                            "ParameterId": 30253,
                            "Length": 12,
                            "DataType": 90,
                            "Unit": 200,
                            "StepNumber": 0,
                            "RealValue": "0000.000e+00",
                        },
                        {
                            "ParameterId": 30264,
                            "Length": 1,
                            "DataType": 2,
                            "Unit": 0,
                            "StepNumber": 0,
                            "RealValue": "0",
                        },
                        {
                            "ParameterId": 30267,
                            "Length": 19,
                            "DataType": 5,
                            "Unit": 0,
                            "StepNumber": 0,
                            "RealValue": "2021-05-18:10:13:58",
                        },
                        {
                            "ParameterId": 30268,
                            "Length": 9,
                            "DataType": 2,
                            "Unit": 0,
                            "StepNumber": 0,
                            "RealValue": "000000003",
                        },
                        {
                            "ParameterId": 30269,
                            "Length": 1,
                            "DataType": 2,
                            "Unit": 0,
                            "StepNumber": 0,
                            "RealValue": "2",
                        },
                        {
                            "ParameterId": 30301,
                            "Length": 3,
                            "DataType": 2,
                            "Unit": 0,
                            "StepNumber": 1,
                            "RealValue": "003",
                        },
                        {
                            "ParameterId": 30302,
                            "Length": 12,
                            "DataType": 90,
                            "Unit": 1,
                            "StepNumber": 1,
                            "RealValue": "0003.411e-02",
                        },
                        {
                            "ParameterId": 30303,
                            "Length": 12,
                            "DataType": 90,
                            "Unit": 50,
                            "StepNumber": 1,
                            "RealValue": "0001.082e+04",
                        },
                        {
                            "ParameterId": 30304,
                            "Length": 12,
                            "DataType": 90,
                            "Unit": 200,
                            "StepNumber": 1,
                            "RealValue": "0002.664e+00",
                        },
                        {
                            "ParameterId": 30305,
                            "Length": 12,
                            "DataType": 90,
                            "Unit": 1,
                            "StepNumber": 1,
                            "RealValue": "0001.141e-02",
                        },
                        {
                            "ParameterId": 30306,
                            "Length": 1,
                            "DataType": 2,
                            "Unit": 0,
                            "StepNumber": 1,
                            "RealValue": "1",
                        },
                        {
                            "ParameterId": 30307,
                            "Length": 12,
                            "DataType": 90,
                            "Unit": 50,
                            "StepNumber": 1,
                            "RealValue": "0001.082e+04",
                        },
                        {
                            "ParameterId": 30310,
                            "Length": 1,
                            "DataType": 2,
                            "Unit": 0,
                            "StepNumber": 1,
                            "RealValue": "1",
                        },
                        {
                            "ParameterId": 30311,
                            "Length": 1,
                            "DataType": 2,
                            "Unit": 0,
                            "StepNumber": 1,
                            "RealValue": "3",
                        },
                        {
                            "ParameterId": 30312,
                            "Length": 1,
                            "DataType": 2,
                            "Unit": 0,
                            "StepNumber": 1,
                            "RealValue": "1",
                        },
                        {
                            "ParameterId": 30313,
                            "Length": 1,
                            "DataType": 2,
                            "Unit": 0,
                            "StepNumber": 1,
                            "RealValue": "3",
                        },
                        {
                            "ParameterId": 30320,
                            "Length": 12,
                            "DataType": 90,
                            "Unit": 50,
                            "StepNumber": 1,
                            "RealValue": "0000.000e+00",
                        },
                        {
                            "ParameterId": 30321,
                            "Length": 12,
                            "DataType": 90,
                            "Unit": 50,
                            "StepNumber": 1,
                            "RealValue": "0000.000e+00",
                        },
                    ],
                    "RevisionsByFields": {
                        "1": [
                            {
                                "HasPrefix": False,
                                "Field": 0,
                                "Index": 20,
                                "Size": 3,
                                "Value": "002",
                                "RawValue": None,
                            },
                            {
                                "HasPrefix": False,
                                "Field": 1,
                                "Index": 23,
                                "Size": 3,
                                "Value": "002",
                                "RawValue": None,
                            },
                            {
                                "HasPrefix": False,
                                "Field": 2,
                                "Index": 26,
                                "Size": 10,
                                "Value": "0000000600",
                                "RawValue": None,
                            },
                            {
                                "HasPrefix": False,
                                "Field": 3,
                                "Index": 36,
                                "Size": 4,
                                "Value": "0000",
                                "RawValue": None,
                            },
                            {
                                "HasPrefix": False,
                                "Field": 4,
                                "Index": 40,
                                "Size": 3,
                                "Value": "076",
                                "RawValue": None,
                            },
                            {
                                "HasPrefix": False,
                                "Field": 5,
                                "Index": 43,
                                "Size": 1756,
                                "Value": "3020001102000000000000000600302010010200000001302020010200000003302030190500000002022-01-10:17:30:583020400102000000013020500202000000002302060020200000000930207008040000000C363005730208011040000000Industreweb302090010200000000302100000400000003021100102000000003021200004000000030213001020000000030214008040000000B353089730215016040000000ETD MT41-150-I0630216003020000000003302170070400000001.50 Nm30218009020000000000000001302190190500000002021-11-04:12:49:40302200190500000002021-11-04:12:49:403022100502000000000000302220000400000003022300902000000000000000030226005020000000000003022700502000000000000302280030200000000003022900302000000000030254003020000000000302300129000100000003.411e-02302310129005000000001.082e+04302700129005000000001.080e+04302320129020000000002.664e+00302330129025100000002.313e+01302340010200000003302710010200000003302350010200000001302360010200000001302370129000100000003.411e-02302380129005000000001.082e+0430239001020000000130240003020000000001302410010200000001302420010200000003302550129000100000001.650e+00302560129000100000000.000e+00302570129005000000001.080e+04302580129005000000000.000e+00302430129080000000000.000e+00302440000400000003024500004000000030246000040000000302470000400000003024800004000000030249000040000000302500000400000003025100004000000030252003020000000000302530129020000000000.000e+00302640010200000000302670190500000002021-05-18:10:13:583026800902000000000000000330269001020000000230301003020000001003303020129000100010003.411e-02303030129005000010001.082e+04303040129020000010002.664e+00303050129000100010001.141e-02303060010200000011303070129005000010001.082e+04303100010200000011303110010200000013303120010200000011303130010200000013303200129005000010000.000e+00303210129005000010000.000e+00",
                                "RawValue": None,
                            },
                        ]
                    },
                    "HeaderData": {
                        "Length": 1799,
                        "Mid": 1202,
                        "Revision": 1,
                        "NoAckFlag": 0,
                        "SpindleID": None,
                        "StationID": None,
                        "UsedAs": None,
                    },
                },
                "Quality": 1.0,
            }
        ],
    }


def cvx_STARTPROGRAM():
    return {
        "TagType": "DataTag",
        "Name": "STARTPROGRAM",
        "DataType": "Object",
        "IOType": "InOut",
        "Units": "",
        "PublishedTimeStamp": zuluTime(),
        "Parameters": {},
        "Readings": [
            {
                "TimeStamp": zuluTime(),
                "Value": {"ID": "0", "VISIONREFNUM": "1", "ACTIONLOGID": "0"},
                "Quality": 1.0,
            }
        ],
    }


def cvx_PROGRAMRESULT():
    return {
        "TagType": "DataTag",
        "Name": "OVERALLRESULT",
        "DataType": "Object",
        "IOType": "InOut",
        "Units": "",
        "PublishedTimeStamp": zuluTime(),
        "Parameters": {},
        "Readings": [
            {
                "TimeStamp": zuluTime(),
                "Value": {"ID": "0", "CASEDATA": "1", "ACTIONLOGID": "0"},
                "Quality": 1.0,
            }
        ],
    }

def tmx_STARTPROGRAM():
    return {
        "TagType": "DataTag",
        "Name": "STARTPROGRAM",
        "DataType": "Object",
        "IOType": "InOut",
        "Units": "",
        "PublishedTimeStamp": zuluTime(),
        "Parameters": {},
        "Readings": [
            {
                "TimeStamp": zuluTime(),
                "Value": {"ID": "0", "VISIONREFNUM": "1", "ACTIONLOGID": "0"},
                "Quality": 1.0,
            }
        ],
    }


def _PROGRAMRESULT():
    return {
        "TagType": "DataTag",
        "Name": "OVERALLRESULT",
        "DataType": "Object",
        "IOType": "InOut",
        "Units": "",
        "PublishedTimeStamp": zuluTime(),
        "Parameters": {},
        "Readings": [
            {
                "TimeStamp": zuluTime(),
                "Value": {"ID": "0", "CASEDATA": "1", "ACTIONLOGID": "0"},
                "Quality": 1.0,
            }
        ],
    }


commandAndControlTopics = [
    ("IW/Mestec/NDATA/CVX/STARTPROGRAM", cvx_STARTPROGRAM),
    ("IW/Mestec/NDATA/CVX/OVERALLRESULT", cvx_PROGRAMRESULT),
    ("IW/Mestec/NDATA/TMX/STARTPROGRAM", tmx_STARTPROGRAM),
    ("IW/Mestec/NDATA/TMX/STARTPROGRAM", tmx_STARTPROGRAM),
]

statusTopics = [
    ("IW/Thales-1/NDATA/B4750287_DATA/TIGHTENINGRESULT", smartTool_TIGHTENINGRESULT),
    ("IW/Thales-1/NDATA/B4750287_DATA/TIGHTENINGDATA", smartTool_TIGHTENINGDATA),
]

omes = [
    *statusTopics
    # *commandAndControlTopics
]
